import { ROLES } from './roles'

export const PERMISSIONS = {
  ADMIN_ONLY: ROLES.ADMIN,
  STUDENT_ONLY: ROLES.STUDENT,
  TEACHER_ONLY: ROLES.TEACHER,
  SCHOOL_ADMIN_ONLY: ROLES.SCHOOL_ADMIN,
  PRINCIPAL_ONLY: ROLES.PRINCIPAL,
}
