export const ROLES = {
  SUPER_ADMIN: 'ROLE_SUPER_ADMIN',
  ADMIN: 'ROLE_ADMIN',
  PRINCIPAL: 'ROLE_PRINCIPAL',
  SCHOOL_ADMIN: 'ROLE_SCHOOL_ADMIN',
  TEACHER: 'ROLE_TEACHER',
  STUDENT: 'ROLE_STUDENT',
}

export const ROLE_PRIORITY = {
  [ROLES.SUPER_ADMIN]: 1,
  [ROLES.ADMIN]: 2,
  [ROLES.PRINCIPAL]: 3,
  [ROLES.SCHOOL_ADMIN]: 4,
  [ROLES.TEACHER]: 5,
  [ROLES.STUDENT]: 6,
}
