import { ROLES } from './roles'

export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  UNAUTHORIZED: '/unauthorized',
  ADMIN: '/admin',
  PRINCIPAL: '/principal',
  SCHOOL: '/school',
  TEACHER: '/teacher',
  STUDENT: '/student',
}

export const DEFAULT_ROUTE_BY_ROLE = {
  [ROLES.SUPER_ADMIN]: ROUTES.ADMIN,
  [ROLES.ADMIN]: ROUTES.ADMIN,
  [ROLES.PRINCIPAL]: ROUTES.PRINCIPAL,
  [ROLES.SCHOOL_ADMIN]: ROUTES.SCHOOL,
  [ROLES.TEACHER]: ROUTES.TEACHER,
  [ROLES.STUDENT]: ROUTES.STUDENT,
}

export const ROUTE_TITLES = {
  '/admin': 'Admin Dashboard',
  '/admin/analytics': 'AI Analytics',
  '/admin/documents': 'Document Management',
  '/admin/assignments': 'Assignments',
  '/admin/submissions': 'Submissions',
  '/admin/schools': 'Schools',
  '/admin/schools/new': 'Create School',
  '/admin/school-admins': 'School Admins',
  '/admin/subscriptions': 'Subscriptions',
  '/admin/audit-logs': 'Audit Logs',
  '/principal': 'Principal Dashboard',
  '/principal/ai': 'AI Dashboard',
  '/principal/documents': 'Document Management',
  '/teacher': 'Teacher Dashboard',
  '/teacher/ai': 'AI Assistant',
  '/teacher/documents': 'Document Management',
  '/student': 'Student Dashboard',
  '/student/courses': 'My Courses',
  '/student/assignments': 'Assignments',
  '/student/submit-assignment': 'Submit Assignment',
  '/student/attendance': 'Attendance',
  '/student/grades': 'Grades & Report Card',
  '/student/study-materials': 'Study Materials',
  '/student/ai-tutor': 'AI Tutor',
  '/student/ai-homework-helper': 'AI Homework Helper',
  '/student/ai-quiz-practice': 'AI Quiz Practice',
  '/student/documents': 'My Documents',
  '/student/calendar': 'Calendar',
  '/student/notifications': 'Notifications',
  '/student/profile': 'My Profile',
  '/student/settings': 'Settings',
  '/student/ai': 'AI Assistant',
  '/unauthorized': 'Access Denied',
  '/admin/chat': 'Chat',
  '/school': 'School Dashboard',
  '/school/profile': 'School Profile',
  '/school/academic-years': 'Academic Years',
  '/school/classes': 'Classes',
  '/school/sections': 'Sections',
  '/school/subjects': 'Subjects',
  '/school/teachers': 'Teachers',
  '/school/students': 'Students',
  '/school/departments': 'Departments',
  '/school/timetable': 'Timetable',
  '/school/announcements': 'Announcements',
  '/school/settings': 'School Settings',
  '/school/documents': 'Documents',
  '/exam/create': 'Create Exam',
  '/exam/manage': 'Manage Exams',
  '/exam/results': 'View Results',
  '/exam/analytics': 'Exam Analytics',
  '/exam/upcoming': 'Upcoming Exams',
  '/exam/my-results': 'My Results',
  '/exam/practice': 'Practice Tests',
  '/knowledge': 'AI Knowledge Center',
  '/knowledge/upload': 'Upload Documents',
  '/knowledge/library': 'Knowledge Library',
  '/knowledge/document': 'Document Details',
  '/knowledge/search': 'AI Search',
  '/knowledge/collections': 'Collections',
  '/knowledge/queue': 'Processing Queue',
  '/knowledge/chat': 'AI Chat',
}
